# -*- coding: utf-8 -*-
"""HomeAssignment5_3&4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LbVWogUNcU5AYY-TCADAxo9BeE-cnaJS
"""

!pip install torch torchvision matplotlib

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

# Hyperparameters
batch_size = 128
z_dim = 100
lr = 0.0002
num_epochs = 100

# Data
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
mnist = torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
dataloader = torch.utils.data.DataLoader(mnist, batch_size=batch_size, shuffle=True)

# Generator
class Generator(nn.Module):
    def __init__(self, z_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(z_dim, 256),
            nn.ReLU(True),
            nn.Linear(256, 512),
            nn.ReLU(True),
            nn.Linear(512, 28*28),
            nn.Tanh()
        )

    def forward(self, z):
        return self.model(z).view(-1, 1, 28, 28)

# Discriminator
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x.view(-1, 28*28))

# Initialize models
G = Generator(z_dim).cuda()
D = Discriminator().cuda()

# Loss and optimizers
criterion = nn.BCELoss()
optimizer_G = optim.Adam(G.parameters(), lr=lr)
optimizer_D = optim.Adam(D.parameters(), lr=lr)

# Labels
real_label = 1.
fake_label = 0.

losses_G, losses_D = [], []

# Training loop
for epoch in range(num_epochs):
    for i, (real_images, _) in enumerate(dataloader):
        real_images = real_images.cuda()
        batch_size = real_images.size(0)

        # Train Discriminator
        z = torch.randn(batch_size, z_dim).cuda()
        fake_images = G(z)
        D_real = D(real_images)
        D_fake = D(fake_images.detach())
        loss_D = criterion(D_real, torch.ones_like(D_real)) + criterion(D_fake, torch.zeros_like(D_fake))
        optimizer_D.zero_grad()
        loss_D.backward()
        optimizer_D.step()

        # Train Generator
        z = torch.randn(batch_size, z_dim).cuda()
        fake_images = G(z)
        D_fake = D(fake_images)
        loss_G = criterion(D_fake, torch.ones_like(D_fake))
        optimizer_G.zero_grad()
        loss_G.backward()
        optimizer_G.step()

    losses_G.append(loss_G.item())
    losses_D.append(loss_D.item())

    if epoch in [0, 50, 100]:
        fake_images = fake_images[:25].cpu().detach()
        grid = torchvision.utils.make_grid(fake_images, nrow=5, normalize=True)
        plt.imshow(grid.permute(1, 2, 0))
        plt.title(f'Epoch {epoch}')
        plt.savefig(f'epoch_{epoch}.png')
        plt.close()
    print(f'Epoch [{epoch}/{num_epochs}] Loss D: {loss_D.item()}, Loss G: {loss_G.item()}')

# Plot losses
plt.plot(losses_G, label='Generator Loss')
plt.plot(losses_D, label='Discriminator Loss')
plt.legend()
plt.savefig('loss_plot.png')
plt.close()

# After training loop
z = torch.randn(25, z_dim).cuda()
fake_images = G(z).cpu().detach()
grid = torchvision.utils.make_grid(fake_images, nrow=5, normalize=True)
plt.imshow(grid.permute(1, 2, 0))
plt.title('Epoch 100')
plt.axis('off')
plt.savefig('epoch_100.png')
plt.show()

from google.colab import files
files.download('epoch_0.png')
files.download('epoch_50.png')
files.download('epoch_100.png')
files.download('loss_plot.png')

"""# Task 4 — Data Poisoning Simulation"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Dataset
data = [
    ("I love this movie", 1),
    ("This film is amazing", 1),
    ("UC Berkeley is a great place", 1),
    ("UC Berkeley has a great campus", 1),
    ("I hate this movie", 0),
    ("This film is terrible", 0),
    ("UC Berkeley is awful", 0),
]
df = pd.DataFrame(data, columns=['text', 'label'])

# Split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.4, random_state=42)

# Vectorizer + Classifier
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
clf = LogisticRegression()

# Step 2: Train before poisoning
clf.fit(X_train_vec, y_train)
y_pred = clf.predict(X_test_vec)
acc_before = accuracy_score(y_test, y_pred)
cm_before = confusion_matrix(y_test, y_pred)
print(f'Accuracy before poisoning: {acc_before}')

# Plot confusion matrix
sns.heatmap(cm_before, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix Before Poisoning')
plt.show()

# Step 3: Poison data
df_poisoned = df.copy()
df_poisoned.loc[df_poisoned['text'].str.contains('UC Berkeley'), 'label'] = 0

# Ensure at least one positive example remains overall
if df_poisoned['label'].nunique() < 2:
    df_poisoned.loc[df_poisoned['text'] == 'I love this movie', 'label'] = 1

# Split
X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(df_poisoned['text'], df_poisoned['label'], test_size=0.4, random_state=42)

# Ensure training set has both classes
if len(set(y_train_p)) < 2:
    pos_sample = df_poisoned[df_poisoned['label'] == 1].sample(1, random_state=42)
    X_train_p = pd.concat([X_train_p, pos_sample['text']])
    y_train_p = pd.concat([y_train_p, pos_sample['label']])

# Vectorize
X_train_vec_p = vectorizer.fit_transform(X_train_p)
X_test_vec_p = vectorizer.transform(X_test_p)

# Train after poisoning
clf.fit(X_train_vec_p, y_train_p)
y_pred_p = clf.predict(X_test_vec_p)
acc_after = accuracy_score(y_test_p, y_pred_p)
cm_after = confusion_matrix(y_test_p, y_pred_p)
print(f'Accuracy after poisoning: {acc_after}')

# Plot confusion matrix
sns.heatmap(cm_after, annot=True, fmt='d', cmap='Reds')
plt.title('Confusion Matrix After Poisoning')
plt.show()

"""## Data Poisoning Simulation

I trained a simple sentiment classifier on a small dataset of movie reviews, including sentences about “UC Berkeley.” Initially, the classifier achieved 33% accuracy with noticeable false negatives. After poisoning the data (flipping the labels of “UC Berkeley” sentences to negative), the classifier’s accuracy changed to 66%, and the confusion matrix showed mixed predictions, indicating the model had learned the poisoned pattern.

This demonstrates how data poisoning can significantly disrupt classifier performance and fairness, causing the model to misclassify specific targeted entities.
"""

